### ISSUE TITLE
Redirection Url Issue

### ISSUE THREAD

**Issue by bhavya999999** [XRM-OSS/D365-UI-Test-Jest-Demo#13]
Hi , 
I am having 

MyUrl/_common/error/errorhandler.aspx?BackUri=https%3a%2f%2fcwl--gbrcrmlivesg609.crm11.dynamics.com%2f&ErrorCode=&Parm0=%0d%0a%0d%0aError%20Details%3a%20An%20unhandled%20exception%20occurred%20during%20the%20execution%20of%20the%20current%20web%20request.%20Please%20review%20the%20stack%20trace%20for%20more%20information%20about%20the%20error%20and%20where%20it%20originated%20in%20the%20code.&RequestUri=%2fmain.aspx%3fappid%3df2e78248-c9f0-ed11-88490022484388ed%252fmain.aspx%253fforceUCI%253d1&user_lcid=1033

**Comment by DigitalFlow** [comment]
Hi @bhavya999999,

What are you executing when you receive the error?

Seems login is somehow going wrong. Any more details or sample code would be great.

Kind regards,
Florian

**Comment by bhavya999999** [comment]
solved upon latest update
