### ISSUE TITLE
Click Ribbon

### ISSUE THREAD

**Issue by imartinflores** [XRM-OSS/D365-UI-Test-Jest-Demo#4]
Hi , any example where you are clicking a ribbon button under more commands ? I ve tried using label and data-id, but is not even expanding more commands.

Thanks!

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

that should usually be done automatically. There is a logic when clicking a button, which searches for it and if it does not find it, clicks the more commands button automatically and retries searching your button.

Can you give me a code example of what you're trying to do?

Kind Regards,
Florian

**Comment by imartinflores** [comment]
Hi @DigitalFlow ! Thanks for your answer. Sure, here is what I am trying to do:

` await xrmTest.Navigation.openUpdateForm("contact", contactid);
  await xrmTest.Button.click({byDataId: "contact|NoRelationship|Form|win.contact.Button22.Button"}, true)`

also tried:

`await xrmTest.Button.click({byLabel: "General"}, true)`

but both returns:   Failed to find button

Thank you!

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

Is it a simple button, or some special one such as a combo button?
Which version of D365-UI-Test and CRM are you using?

Kind Regards,
Florian

**Comment by imartinflores** [comment]
Hi @DigitalFlow !
Its a simple ribbon button, inside of more commands, its to create incidents. I know we have the option to openCreateForm()
but this is because we had an issue with ribbon not being clickable, so I would like to check. I am using latest version, just updated it this morning to make sure. And Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online.

I have tried with another ribbon button, which does not have "More commands" and it works

Thanks!

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

First up: Does the "More Commands" menu even open at your side?

If yes, can you manage to show me the HTML of the button that you are trying to click?
It's a little annoying to get it, you will probably have to add a DOM breakpoint inside the browser debugger, as the more commands overlay will disappear once you click anywhere else (including the debugger).

Kind Regards,
Florian

**Comment by imartinflores** [comment]
Hey @DigitalFlow !

From what I could see, is not even opening the more commands.
Sure, here you have the more commands:
![image](https://user-images.githubusercontent.com/17011557/112306623-e97a7880-8c97-11eb-8408-d6f45d338024.png)

And the button I am trying to click:
![image](https://user-images.githubusercontent.com/17011557/112306870-38281280-8c98-11eb-8b86-f35bdc0ca5ab.png)

Let me know if that helps.
Thanks!

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

could you copy the HTML in here? It seems that there is quite some stuff missing.
You can just right click on the nodes and click "Edit as HTML", then you can copy it.

It seems however that your button is not a normal button, but a SplitButton. Might be that there is something special in how the HTML is generated for these. 

Kind Regards,
Florian

**Comment by imartinflores** [comment]
Sure @DigitalFlow :

This is the more commands HTML:

`<li id="contact|NoRelationship|Form|win.contact.AddNewCase.SplitButton.Menu$splitButtonId_button2" role="presentation" title="New Case

Creates a new case for this player" data-expanded="true" class="pa-oe pa-y pa-nx pa-nz "><button id="contact|NoRelationship|Form|win.contact.AddNewCase.SplitButton.Menu$splitButtonId_button2$button" aria-label="New Case More Commands" aria-describedby="flyoutButton_description_contact|NoRelationship|Form|win.contact.AddNewCase.SplitButton.Menu$splitButtonId_button2 openflyout_description_contact|NoRelationship|Form|win.contact.AddNewCase.SplitButton.Menu$splitButtonId_button2" aria-expanded="true" aria-haspopup="true" role="menuitem" tabindex="0" data-id="contact|NoRelationship|Form|win.contact.AddNewCase.SplitButton.Menu$splitButtonId" data-lp-id="Form:contact-contact|NoRelationship|Form|win.contact.AddNewCase.SplitButton.Menu$splitButtonId" type="button" class="pa-ak pa-jg pa-fs pa-fx pa-aj pa-ld pa-at pa-cn pa-bp flexbox" aria-owns="contact|NoRelationship|Form|win.contact.AddNewCase.SplitButton.Menu$splitButtonId_button2_flyout" style="outline-color: rgb(102, 102, 102);"><span aria-hidden="true" class="pa-az pa-ah pa-a pa-gs "><span class="pa-jg pa-cd pa-fj pa-fm pa-of pa-oa pa-ob pa-jh "><span class="symbolFont ChevronDown-symbol pa-oc pa-cg pa-bd pa-cc "></span></span><span class="pa-gu pa-bd pa-oc pa-v pa-e pa-cm pa-od pa-cl "></span></span></button><span id="flyoutButton_description_contact|NoRelationship|Form|win.contact.AddNewCase.SplitButton.Menu$splitButtonId_button2" class="pa-w ">Creates a new case for this player</span><span id="openflyout_description_contact|NoRelationship|Form|win.contact.AddNewCase.SplitButton.Menu$splitButtonId_button2" class="pa-w ">Press Enter to open flyout</span></li>`

And this is the one trying to click:

`<li id="contact|NoRelationship|Form|win.contact.AddNewCase.Command.General02" role="presentation" title="General" class="pa-bh "><button id="contact|NoRelationship|Form|win.contact.AddNewCase.Command.General02-button" aria-label="General" role="menuitem" tabindex="0" data-id="contact|NoRelationship|Form|win.contact.Button22.Button" data-lp-id="Form:contact-contact|NoRelationship|Form|win.contact.Button22.Button" type="button" class="pa-oc pa-bh pa-ak pa-fx pa-aj pa-oa pa-ob pa-jd pa-je pa-ah pa-at pa-ld flexbox" style="outline-color: rgb(102, 102, 102);"><span aria-hidden="true" class="pa-az pa-at pa-ah pa-a pa-gs "><span class="pa-jg pa-gy pa-cd pa-bd pa-a pa-at "><img src="/%7b637521788010000152%7d/webresources/win_ico_case_16x16svg" alt="" class="pa-kw pa-cg pa-bd pa-cc pa-og "></span><span class="pa-gu pa-bd pa-oc pa-cl pa-v pa-e pa-cm pa-po ">General</span></span></button></li>`

Hope it helps more now, again, let me know if you need more help from me.

Thanks a lot

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

I think there is something wrong with your overflow / "More Commands" button. It should look totally different.
The important part is the `data-id="OverflowButton"` property on its button HTML element:

```HTML
    <button id="OverflowButton_button24$button" aria-label="Weitere Befehle für Kontakt" aria-describedby=" openflyout_description_OverflowButton_button24" aria-expanded="false" aria-haspopup="true" role="menuitem" tabindex="0" data-id="OverflowButton" data-lp-id="Form:contact-OverflowButton" type="button" class="pa-ak pa-ka pa-fp pa-fu pa-da pa-aj pa-at pa-pj flexbox">

```

Can you post a screenshot of what the button that you see as overflow button looks like? Should look something like this:
![image](https://user-images.githubusercontent.com/4287938/112447487-a977cc00-8d51-11eb-9898-00d4f7995d2e.png)

Kind Regards,
Florian

**Comment by imartinflores** [comment]
Sure @DigitalFlow , it does not look like that definitely. Attached you have a screenshot.
That way is clicking the "More Commands" and I need to wait for the "General" button to appear in the flyout before clicking it then. That will help.

![image](https://user-images.githubusercontent.com/17011557/112460460-d4185380-8d56-11eb-9f14-496c4ed7d6cc.png)

Thank you!

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

I see, so this is really a split button, not the overflow button.

Did you try my approach? The code that I sent should first expand your split button, wait for the UI to become idle and then click the General button inside the expanded Panel.
Should do the trick. 

Kind Regards,
Florian

**Comment by imartinflores** [comment]
Hi @DigitalFlow , yeah, tried that, but seems like I need to add a Wait between clicks (More Commands and General) cause without it, it clicks the More Commands, but then fails cause the General button is not displayed immediately, so I will try to add a wait between. Thanks so much for looking into it, appreciate it!

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

That's strange, usually it should wait at least 2 seconds on its own after clicking the first button.
But ok, adding a wait for the second button should be the way to go then.

Glad to have helped and glad that you're using this framework :).

Please close this issue once you got it working.

Kind Regards,
Florian
