### ISSUE TITLE
Parallelism

### ISSUE THREAD

**Issue by imartinflores** [XRM-OSS/D365-UI-Test-Jest-Demo#5]
Hi @DigitalFlow ! Sorry to bother, just a general question. Is there anyway, by using Jest as in the example, to run multiple .spec files in parallel ?

i.e: I have "Activities.spec.ts" and "Case.spec.ts" , I have found in the jest.config.js file, the "include" option with "./spec" , so it is picking all the spec files under that folder, but running them sequentially, is there anything I need to add ?

Also, is there anyway to run them in a selenium grid ?

thanks a lot!

**Comment by DigitalFlow** [comment]
Hi @DigitalFlow,

Yes you can run tests in parallel. 
This is even the default of jest, all .spec files are executed in parallel by default.

You just need to remove the `--runInBand` parameter inside the [package.json](https://github.com/XRM-OSS/D365-UI-Test-Jest-Demo/blob/master/package.json#L7), then they are executed in parallel again.

Selenium Grid does not support playwright as it seems. 

Kind regards,
Florian

**Comment by imartinflores** [comment]
Thanks a lot as always @DigitalFlow !
